version: "3.9"
services:
  mongodb:
    image: mongo
    ports:
    - '27017:27017'
    env_file: 
      - ../xc-league-backend/env/mongo.env
  mongo-seed:
    build: 
      context: ../xc-league-backend/mongo-seed
      dockerfile: Dockerfile
    links:
      - mongodb
  backend:
    build:
      context: ../xc-league-backend
      dockerfile: Dockerfile
    ports:
       - '3000:3000'
    volumes: 
      - ../xc-league-backend:/app
      - /app/node_modules
    env_file: 
      - ../xc-league-backend/env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: 
      context: ../xc-league-frontend
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    volumes: 
      - ../xc-league-frontend/src:/app/src
      - /app/node_modules
    env_file: ../xc-league-frontend/.env
    stdin_open: true
    tty: true
    depends_on: 
      - backend
